source "https://rubygems.org"

gem "sinatra"
gem 'sinatra-cross_origin'
gem "json"
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord'
gem "sqlite3"      
gem 'rake'
gem 'yaml'
gem "rspec"
gem "rackup", "~> 2.2"
gem "puma", "~> 6.6"
